spring:
  mongodb:
    uri: mongodb://localhost:27017/controle_financeiro

  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
  address: 0.0.0.0
  port: 8080